### ISSUE TITLE
Admin environment breaks in EPiServer 10

### ISSUE THREAD

**Issue by rbaarda** [markeverard/POSSIBLE.RobotsTxtHandler#8]
When trying to manage the robots.txt content in admin mode the following error occurs in EPiServer 10:

`Exception information: 
    Exception type: MissingMethodException 
    Exception message: Method not found: 'Void EPiServer.CacheManager.Add(System.String, System.Object)'.
   at POSSIBLE.RobotsTxtHandler.RobotsContentService.GetRobotsContent(String robotsKey)
   at POSSIBLE.RobotsTxtHandler.UI.Controllers.RobotsTxtAdminController.Index()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at System.Web.Mvc.Controller.ExecuteCore()
   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.ProcessController(IController controller)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
`

**Comment by adrianchandler** [comment]
@markeverard I see there is a pull request that someone has submitted to fix EPiServer 10 issues - any chance you could merge and update nuget package?

**Comment by whyleee** [comment]
+1 Please accept #7 pull request and release a new package

**Comment by markeverard** [comment]
An updated Nuget package 3.0.0 has been submitted to Episerver thanks to @sebbe
